# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Feb 14 18:25:49 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(600, 600)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.etatsGroupBox = QtGui.QGroupBox(self.splitter)
        self.etatsGroupBox.setObjectName(_fromUtf8("etatsGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.etatsGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.etatsListView = QtGui.QListView(self.etatsGroupBox)
        self.etatsListView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.etatsListView.setObjectName(_fromUtf8("etatsListView"))
        self.horizontalLayout.addWidget(self.etatsListView)
        self.hypothesesGroupBox = QtGui.QGroupBox(self.splitter)
        self.hypothesesGroupBox.setObjectName(_fromUtf8("hypothesesGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.hypothesesGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.hypothesesListView = QtGui.QListView(self.hypothesesGroupBox)
        self.hypothesesListView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.hypothesesListView.setObjectName(_fromUtf8("hypothesesListView"))
        self.horizontalLayout_2.addWidget(self.hypothesesListView)
        self.AgentsGroupBox = QtGui.QGroupBox(self.splitter)
        self.AgentsGroupBox.setObjectName(_fromUtf8("AgentsGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.AgentsGroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.agentsTreeView = QtGui.QTreeView(self.AgentsGroupBox)
        self.agentsTreeView.setObjectName(_fromUtf8("agentsTreeView"))
        self.horizontalLayout_3.addWidget(self.agentsTreeView)
        self.verticalLayout_4.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menuEdition = QtGui.QMenu(self.menubar)
        self.menuEdition.setObjectName(_fromUtf8("menuEdition"))
        self.menuM_thode_de_calcule = QtGui.QMenu(self.menuEdition)
        self.menuM_thode_de_calcule.setObjectName(_fromUtf8("menuM_thode_de_calcule"))
        self.menuHypotheses = QtGui.QMenu(self.menuEdition)
        self.menuHypotheses.setObjectName(_fromUtf8("menuHypotheses"))
        self.menuEtats_du_monde = QtGui.QMenu(self.menuEdition)
        self.menuEtats_du_monde.setObjectName(_fromUtf8("menuEtats_du_monde"))
        self.menuAgents = QtGui.QMenu(self.menuEdition)
        self.menuAgents.setObjectName(_fromUtf8("menuAgents"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionTitre = QtGui.QAction(MainWindow)
        self.actionTitre.setObjectName(_fromUtf8("actionTitre"))
        self.actionDescription = QtGui.QAction(MainWindow)
        self.actionDescription.setObjectName(_fromUtf8("actionDescription"))
        self.actionOuvrir = QtGui.QAction(MainWindow)
        self.actionOuvrir.setObjectName(_fromUtf8("actionOuvrir"))
        self.actionEnregistrer = QtGui.QAction(MainWindow)
        self.actionEnregistrer.setObjectName(_fromUtf8("actionEnregistrer"))
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setMenuRole(QtGui.QAction.QuitRole)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.actionDempster_Shafer = QtGui.QAction(MainWindow)
        self.actionDempster_Shafer.setCheckable(True)
        self.actionDempster_Shafer.setChecked(True)
        self.actionDempster_Shafer.setObjectName(_fromUtf8("actionDempster_Shafer"))
        self.actionDubois_Prade = QtGui.QAction(MainWindow)
        self.actionDubois_Prade.setCheckable(True)
        self.actionDubois_Prade.setObjectName(_fromUtf8("actionDubois_Prade"))
        self.actionAjouterEtat = QtGui.QAction(MainWindow)
        self.actionAjouterEtat.setObjectName(_fromUtf8("actionAjouterEtat"))
        self.actionSupprimerEtat = QtGui.QAction(MainWindow)
        self.actionSupprimerEtat.setObjectName(_fromUtf8("actionSupprimerEtat"))
        self.actionAjouterHypothese = QtGui.QAction(MainWindow)
        self.actionAjouterHypothese.setObjectName(_fromUtf8("actionAjouterHypothese"))
        self.actionSupprimerHypothese = QtGui.QAction(MainWindow)
        self.actionSupprimerHypothese.setObjectName(_fromUtf8("actionSupprimerHypothese"))
        self.actionAjouterAgent = QtGui.QAction(MainWindow)
        self.actionAjouterAgent.setObjectName(_fromUtf8("actionAjouterAgent"))
        self.actionSupprimerAgent = QtGui.QAction(MainWindow)
        self.actionSupprimerAgent.setObjectName(_fromUtf8("actionSupprimerAgent"))
        self.actionModifierAgent = QtGui.QAction(MainWindow)
        self.actionModifierAgent.setObjectName(_fromUtf8("actionModifierAgent"))
        self.menuFichier.addAction(self.actionTitre)
        self.menuFichier.addAction(self.actionDescription)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuFichier.addAction(self.actionEnregistrer)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionQuitter)
        self.menuM_thode_de_calcule.addAction(self.actionDempster_Shafer)
        self.menuM_thode_de_calcule.addAction(self.actionDubois_Prade)
        self.menuHypotheses.addAction(self.actionAjouterHypothese)
        self.menuHypotheses.addAction(self.actionSupprimerHypothese)
        self.menuEtats_du_monde.addAction(self.actionAjouterEtat)
        self.menuEtats_du_monde.addAction(self.actionSupprimerEtat)
        self.menuAgents.addAction(self.actionAjouterAgent)
        self.menuAgents.addAction(self.actionSupprimerAgent)
        self.menuAgents.addAction(self.actionModifierAgent)
        self.menuEdition.addAction(self.menuM_thode_de_calcule.menuAction())
        self.menuEdition.addSeparator()
        self.menuEdition.addAction(self.menuEtats_du_monde.menuAction())
        self.menuEdition.addAction(self.menuHypotheses.menuAction())
        self.menuEdition.addAction(self.menuAgents.menuAction())
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuEdition.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculateur", None))
        self.etatsGroupBox.setTitle(_translate("MainWindow", "Etats du monde", None))
        self.hypothesesGroupBox.setTitle(_translate("MainWindow", "Hypothèses", None))
        self.AgentsGroupBox.setTitle(_translate("MainWindow", "Agents", None))
        self.menuFichier.setTitle(_translate("MainWindow", "&Fichier", None))
        self.menuEdition.setTitle(_translate("MainWindow", "&Edition", None))
        self.menuM_thode_de_calcule.setTitle(_translate("MainWindow", "Méthode de calcule", None))
        self.menuHypotheses.setTitle(_translate("MainWindow", "Hypothèses", None))
        self.menuEtats_du_monde.setTitle(_translate("MainWindow", "Etats du monde", None))
        self.menuAgents.setTitle(_translate("MainWindow", "Agents", None))
        self.actionTitre.setText(_translate("MainWindow", "Titre", None))
        self.actionTitre.setShortcut(_translate("MainWindow", "Ctrl+T", None))
        self.actionDescription.setText(_translate("MainWindow", "Description", None))
        self.actionDescription.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir", None))
        self.actionOuvrir.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionEnregistrer.setText(_translate("MainWindow", "Enregistrer", None))
        self.actionEnregistrer.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter", None))
        self.actionQuitter.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionDempster_Shafer.setText(_translate("MainWindow", "Dempster-Shafer", None))
        self.actionDubois_Prade.setText(_translate("MainWindow", "Dubois-Prade", None))
        self.actionAjouterEtat.setText(_translate("MainWindow", "Ajouter", None))
        self.actionAjouterEtat.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.actionSupprimerEtat.setText(_translate("MainWindow", "Supprimer", None))
        self.actionSupprimerEtat.setShortcut(_translate("MainWindow", "Ctrl+Shift+E", None))
        self.actionAjouterHypothese.setText(_translate("MainWindow", "Ajouter", None))
        self.actionAjouterHypothese.setShortcut(_translate("MainWindow", "Ctrl+H", None))
        self.actionSupprimerHypothese.setText(_translate("MainWindow", "Supprimer", None))
        self.actionSupprimerHypothese.setShortcut(_translate("MainWindow", "Ctrl+Shift+H", None))
        self.actionAjouterAgent.setText(_translate("MainWindow", "Ajouter", None))
        self.actionAjouterAgent.setShortcut(_translate("MainWindow", "Ctrl+G", None))
        self.actionSupprimerAgent.setText(_translate("MainWindow", "Supprimer", None))
        self.actionSupprimerAgent.setShortcut(_translate("MainWindow", "Ctrl+Shift+G", None))
        self.actionModifierAgent.setText(_translate("MainWindow", "Modifier", None))
        self.actionModifierAgent.setShortcut(_translate("MainWindow", "Alt+G", None))

